FROM ubuntu:25.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y --allow-releaseinfo-change --allow-unauthenticated

# Install necessary libraries
RUN apt-get install -y --no-install-recommends \
    libwayland-egl1 \
    glmark2-wayland glmark2-es2-wayland \
    libgl1-mesa-dri \
    glmark2-wayland libgl1 libegl1 libgles2 strace

ENV WAYLAND_DISPLAY=wayland-0

# Can run either or, as we instaleld both packages
#CMD ["glmark2-wayland"]
CMD ["glmark2-es2-wayland"]
